baseURL = "https://docs.lpda.se/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "LPDA docs"
theme = "hugo-theme-relearn"

[params]
  editURL = "https://github.com/peter-andersson/docs.lpda.se/edit/main/content/"
  description = "LPDA docs"
  author = "Peter Andersson"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = true
  disableMermaid = true
  disableToc = true
  disableMathJax = true
  titleSeparator = "-"
  themeVariant = "relearn-dark"

[outputs]
home = [ "HTML", "RSS", "JSON"]